# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

source 'https://cdn.cocoapods.org/'

platform :ios, '15.1'
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'BubblBridgeSandbox' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'BubblSDK', :git => 'https://github.com/bubbl-repo/bubbl-ios-sdk.git', :tag => '2.1.6'
  pod 'FirebaseCore', :modular_headers => true
  pod 'Firebase/Messaging'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Ensure dSYMs are generated for release builds (fixes missing dSYM uploads)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        next unless config.name == 'Release'
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      end
    end

    # Remove macOS 14+ script sandbox attributes (Bubbl pod requirement)
    require 'find'
    Find.find('Pods/Target Support Files') do |path|
      next unless path.end_with?('.sh')
      system('xattr', '-d', 'com.apple.quarantine', path) rescue nil
      system('xattr', '-d', 'com.apple.provenance', path) rescue nil
      system('chmod', '+x', path)
    end
  end
end
